#!/bin/bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

set -x

cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File @generated by generate-contributors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See generate-contributors .sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
